### ISSUE TITLE
Mảng bị trùng khi nhiều người nhắn đến cùng 1 lúc

### ISSUE THREAD

**Issue by dphoanghiep1998** [dphoanghiep1998/SE04-24.1#11]

**Comment by vutran1305** [comment]
chi tiết như thế nào?

**Comment by dphoanghiep1998** [comment]
chi tiết là nếu có nhiều hơn 2 người dùng nhắn tin đến bot, thì mảng toàn cục sử dụng bị chèn liên tục => bug

**Comment by vutran1305** [comment]
Thử đẩy vào hàm luôn xem được không

**Comment by dphoanghiep1998** [comment]
đã fix được bằng cách tạo dict trong đó key là psid và value là mảng chưa tin nhắn
