### ISSUE TITLE
Lấy dữ liệu text người dùng qua hội thoại như thế nào ?

### ISSUE THREAD

**Issue by dphoanghiep1998** [dphoanghiep1998/SE04-24.1#12]

**Comment by dphoanghiep1998** [comment]
dựa vào log, chúng ta đã thiết lập được webhook rồi, theo hàm post lấy received_message , đó là 1 json object với các trường,.. chúng ta catch nó là text hoặc là postback, từ đó lấy ra các thông tin yêu cầu

**Comment by vutran1305** [comment]
Cho vd về một đoạn thông tin được không?

**Comment by dphoanghiep1998** [comment]
![anh1](https://user-images.githubusercontent.com/67047096/103404646-f438dc00-4b86-11eb-96f9-fbc31daa2ea5.png)

**Comment by dphoanghiep1998** [comment]
đây là dữ liệu mà chúng ta lấy được có các entity , intent tùy mình sử dụng theo mục đích như nào

**Comment by dphoanghiep1998** [comment]
sử dụng post women hoặc logs để xem thông tin

**Comment by dphoanghiep1998** [comment]
done

**Comment by vutran1305** [comment]
À ok hiểu r
