### ISSUE TITLE
wit.ai không cho xóa wit$phone_number mặc định (xóa entity)

### ISSUE THREAD

**Issue by dphoanghiep1998** [dphoanghiep1998/SE04-24.1#14]
có nên để lại không hay tạo app khác?

**Comment by vutran1305** [comment]
thôi giữ lại đi mình catch nó được xóa đi phí dữ liệu đã train

**Comment by dphoanghiep1998** [comment]
ok ông thế ông có giải pháp nào không?

**Comment by vutran1305** [comment]
cần suy nghĩ

**Comment by hieutrungtran2205** [comment]
nghiên cứu tí đã cứ bình tĩnh bro

**Comment by dphoanghiep1998** [comment]
thôi cứ giữ lại vậy

**Comment by huyhoanghus** [comment]
vote giữ lại
