### ISSUE TITLE
Làm sao để nhập lại thông tin khi nhập sai?

### ISSUE THREAD

**Issue by vutran1305** [dphoanghiep1998/SE04-24.1#16]
t thấy lúc nhập xog thông tin thì sẽ tự động nhảy đến 1 trường mới , muốn nhập lại thì phải làm mới hội thoại khá mất thời gian , làm thế nào để khắc phục nhỉ?

**Comment by dphoanghiep1998** [comment]
tạm thời chưa tìm được phương pháp tập trung hoàn thiện proj
