### ISSUE TITLE
Làm sao để tích hợp chatbot vào trang web ? 

### ISSUE THREAD

**Issue by vutran1305** [dphoanghiep1998/SE04-24.1#17]

**Comment by vutran1305** [comment]
Có thể tham khảo ở đây https://wiki.matbao.net/kb/huong-dan-tich-hop-facebook-chat-vao-website-ma-khong-can-dung-plugin/

**Comment by dphoanghiep1998** [comment]
web đã được update => cần phải căn chỉnh

**Comment by dphoanghiep1998** [comment]
đã add được plugin vào web

**Comment by huyhoanghus** [comment]
t tham khảo link này https://thinhweb.com/huong-dan-kich-hoat-nen-tang-chat-messenger-de-tich-hop-chatbox-vao-website/
