### ISSUE TITLE
Tìm hiểu học máy ( mechine learning) và các tool hỗ trợ

### ISSUE THREAD

**Issue by dphoanghiep1998** [dphoanghiep1998/SE04-24.1#2]
# góp ý : tool hỗ trợ học máy : wit.ai nền tảng facebook.

**Comment by vutran1305** [comment]
# Nền tảng:
-Messenger-plaform
# Ngôn ngữ sử dụng :
- Javascript
# Công cụ hỗ trợ :
- VS studio code
-  Github
-  Heroku
- Facebook
# Tài liệu tham khảo:
- Youtube(video hướng dẫn)
- FaceBook(hướng dẫn của fb )
- Google(Tra cứu)
# Tool
- Wit.a
- vntk

**Comment by dphoanghiep1998** [comment]
Things to do : 
Tìm hiểu Entity, Traits, Intents, .
Cách train data

**Comment by dphoanghiep1998** [comment]
cái này ae sử dụng wit.ai đi , tool dễ sử dụng mà cũng là của facebook

**Comment by vutran1305** [comment]
ok cái này giải thích trước đó rồi nhé

**Comment by dphoanghiep1998** [comment]
ok > done
