### ISSUE TITLE
bot không nhận diện đc tổng tiền thiệt hại

### ISSUE THREAD

**Issue by hieutrungtran2205** [dphoanghiep1998/SE04-24.1#22]
![image](https://user-images.githubusercontent.com/71141036/103442104-d3a37b80-4c85-11eb-8852-b3623cf5cfcc.png)

**Comment by dphoanghiep1998** [comment]
những cái trên wit.ai sẽ hiểu là number , để nhận diện được số tiền cần phải gõ thêm " đồng" hoặc "$",vv.
=> done

**Comment by hieutrungtran2205** [comment]
nếu vậy nên để bot chú thích thêm để ng dùng dễ sử dụng
