### ISSUE TITLE
Tạo kịch bản hội thoại cơ bản giữa bot và người dùng

### ISSUE THREAD

**Issue by dphoanghiep1998** [dphoanghiep1998/SE04-24.1#4]

**Comment by vutran1305** [comment]
--Nền tảng:
-Messenger-plaform
--Công cụ hỗ trợ :
- VS studio code
-  Github
-  Heroku
- wit.ai
- -Facebook
--Tài liệu tham khảo:
-Youtube
-FaceBook(hướng dẫn của fb )
- Google

**Comment by vutran1305** [comment]
#Nền tảng:
-Messenger-plaform
#Công cụ hỗ trợ :
- VS studio code
-  Github
-  Heroku
- Facebook
#Tài liệu tham khảo:
- Youtube(video hướng dẫn)
- FaceBook(hướng dẫn của fb )
- Google(Tra cứu)
#Tool
- Wit.ai

**Comment by dphoanghiep1998** [comment]
# Chú ý

 Tạo kich bản vào trong file readme.md

**Comment by dphoanghiep1998** [comment]
kịch bản update #2 vào kcihban.md

https://docs.google.com/document/d/1uEBA5kTpQLVybgBhq-XEtitZIePBiiptl1azr265jZQ/edit
link doc
