### ISSUE TITLE
Chatbot đẩy dữ liệu lên database

### ISSUE THREAD

**Issue by dphoanghiep1998** [dphoanghiep1998/SE04-24.1#5]
Tìm hiểu cách chatbot đẩy dữ liệu lên 1 db nào đó

**Comment by hieutrungtran2205** [comment]
tham khảo cái này xem đc ko https://datazenit.com/heroku-data-explorer.html

**Comment by dphoanghiep1998** [comment]
> tham khảo cái này xem đc ko https://datazenit.com/heroku-data-explorer.html

hiểu có thể nêu quy trình lên đây ko, nếu khả thi thì sẽ làm

**Comment by hieutrungtran2205** [comment]
đây là 1 công cụ quản lý database của heroku, đăng nhập tài khoản heroku vào để xem

**Comment by vutran1305** [comment]
ngon luôn

**Comment by vutran1305** [comment]
thế dùng cái này luôn

**Comment by dphoanghiep1998** [comment]
các bạn ơi mình cần quy trình cụ thể đấy ?

**Comment by dphoanghiep1998** [comment]
mình đã đẩy được data lên heroku posgressql rồi nhé.
=> done

**Comment by huyhoanghus** [comment]
hoặc làm theo link này cũng đc https://w
ww.youtube.com/watch?v=irIXDPnvRvA
