### ISSUE TITLE
Triển khai Node.js lên Heroku

### ISSUE THREAD

**Issue by hieutrungtran2205** [dphoanghiep1998/SE04-24.1#6]
- Dowload Heroku CLI, tạo tài khoản Heroku.
- Đăng nhập và tạo app mới.
- Tại VScode:
	+ Login:
		$ heroku login
	+ Create a new Git repository:
		$ cd my-project/
		$ git init
		$ heroku git:remote -a appname
	+ Deploy application:
		$ git add .
		$ git commit -m "deploy heroku"
		$ git push heroku master
- Cấu hình các tham số: PORT, VERIFY_TOKEN, MY_VERIFY_TOKEN,...

**Comment by dphoanghiep1998** [comment]
Gì vậy má

Vào Th 4, 30 thg 12, 2020 lúc 16:20 hieutrungtran2205 <
notifications@github.com> đã viết:

**Comment by dphoanghiep1998** [comment]
ok, tìm cách đẩy dữ liệu lên db đi

**Comment by huyhoanghus** [comment]
tham khảo https://www.hoangweb.com/hosting-domain/cai-dat-nodejs-socket-io-len-heroku-server
