### ISSUE TITLE
Tạo Page trên Facebook, setup webhook , các tham số cần thiết

### ISSUE THREAD

**Issue by dphoanghiep1998** [dphoanghiep1998/SE04-24.1#8]

**Comment by dphoanghiep1998** [comment]
Nêu lên cách tạo page, setup page, tóm lại là nền.

**Comment by hieutrungtran2205** [comment]
- Tạo fanpage trên facebook, thêm nút gửi tin nhắn.
- Truy cập https://developers.facebook.com/apps/ để tạo app mới
	+ Chọn set up Messenger
	+ Thêm fanpage vừa lập, tạo mã xác minh
- Copy mã xác minh vào tham số PAGE_ACCESS_TOKEN trong file .env, đồng thời tự đặt mã cho tham số VERIFY_TOKEN.
- Cấu hình tham số trên Heroku.
- Kết nối webhook
	+ Thêm URL gọi lại: copy đường link app trên Heroku thêm đuôi /webhook
	+ Mã xác minh: là mã của tham số VERIFY_TOKEN

**Comment by vutran1305** [comment]
![134254843_761592714452856_881359615797646967_n](https://user-images.githubusercontent.com/72801957/103404151-25181180-4b85-11eb-9b62-b4401b335b6b.png)

**Comment by vutran1305** [comment]
URL gọi lại : đường dẫn webhook sau khi đã deploy lên heroku
MÃ xác minh : Mã để xác minh webhook của mình

**Comment by dphoanghiep1998** [comment]
ok bạn vậy còn setup nlp như thế nào ?

**Comment by vutran1305** [comment]
![134406497_441793370339333_3897420994507115818_n](https://user-images.githubusercontent.com/72801957/103404269-8a6c0280-4b85-11eb-8acd-0eb1d8128e81.png)

**Comment by vutran1305** [comment]
![134](https://user-images.githubusercontent.com/72801957/103404354-c2734580-4b85-11eb-94dd-1a8253d64c5f.png)

**Comment by vutran1305** [comment]
Sử tool có sẵn wit.ai của fb ấy

**Comment by vutran1305** [comment]
Các bước setup có trong gg doc này : 
https://wit.ai/docs?fbclid=IwAR1zTXKzAL5aybI1ssaC9jPDh8GZ5rnTNfBRJiXxSMxHP94pQk2ABBg2OFY
Đây là hướng dẫn của wit.ai

**Comment by dphoanghiep1998** [comment]
ok => close iss
